name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  X_PYTHON_MIN_VERSION: "3.11"

jobs:
  test:
    # This job runs the unittests on the python versions specified down at the matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.X_PYTHON_MIN_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test with coverage + unittest
        run: |
          coverage run --source=bibtex_linter -m unittest
      - name: Report test coverage
        if: ${{ always() }}
        run: |
          coverage report -m

  static-analysis:
    # This job runs static code analysis, namely pycodestyle and mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.X_PYTHON_MIN_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Check typing with MyPy
        run: |
          mypy --strict bibtex_linter test
      - name: Check code style with PyCodestyle
        run: |
          pycodestyle --count --max-line-length 120 bibtex_linter test
